#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi


# Customize to your needs...

# Update Pretzo
alias update_pretzo="cd ~/.zprezto/ && git submodule foreach git reset --hard && git pull && git submodule update --init --recursive"

alias show_hidden_files="defaults write com.apple.finder AppleShowAllFiles YES; killall Finder /System/Library/CoreServices/Finder.app"

alias hide_hidden_files="defaults write com.apple.finder AppleShowAllFiles NO; killall Finder /System/Library/CoreServices/Finder.app
"
# Switch to master branch and pull
alias gmp="git co master && git pull --prune"

# Run migrations
alias dbm="bin/rake db:migrate && sr"

# Undo schema.rb changes
alias sr="git co -- db/structure.sql"

# Git goodies
alias gg='noglob gg'

# script/server
alias ss="script/server"

# git jk
alias gitjk="history 10 | tail -r | gitjk_cmd"

# Make `rm` put stuff in trash
alias rm="trash"

# zmv ftw
autoload -U zmv
# alias for zmv for no quotes
# mmv *.c.orig orig/*.c
alias mmv='noglob zmv -W'

# fix duplicate "open with" entries
alias fixopenwith='/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -kill -r -domain local -domain system -domain user && killall Finder'

# This is needed for hub/git autocompletion
setopt complete_aliases

export EDITOR=vim
export VISUAL=vim

export GOPATH=$HOME
export PATH="$HOME/bin:$PATH"
export PATH="/opt/boxen/nodenv/versions/v0.10/bin:$PATH"
export PATH="$PATH:$GOPATH/bin"

export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"
eval "$(fasd --init auto)"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
